[workspace]
resolver = "2"

members = [
    "horizon-error",
    "horizon-svc",
    "horizon-svc-codegen",
    "horizon-rt",
    "horizon-global",
    "horizon-sync",
    "horizon-ipc",
    "horizon-ipcdef",
    "horizon-ipcdef-codegen",
]

