cargo-features = ["per-package-target"]

[package]
name = "horizon-rt"
version = "0.1.0"
edition = "2021"
default-target = "aarch64-unknown-none"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
